services:
  postgres:
    image: postgres:17
    container_name: pg-trader
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  trader:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trader
    depends_on:
      - postgres
    environment:
      DB_DRIVER: postgres
      API_KEY: ${API_KEY}
      API_SECRET: ${API_SECRET}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
volumes:
  pgdata:
    driver: local
